name: {Template}

targets:
    {Template}:
        type: application
        platform: iOS
        deploymentTarget: "13.0"
        sources: [{Template}]
        preBuildScripts:
            - path: scripts/lint.sh
              name: "Run Lint"
        postBuildScripts:
            - path: scripts/format.sh
              name: "Run Format"
        settings:
            PRODUCT_BUNDLE_IDENTIFIER: {BUNDLE_IDENTIFIER}
